---
# tasks file for easy_rsa

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - easy_rsa

- name: CentosOS Pre-req
  block:
    - include: CentOS.yml

    - set_fact:
        easy_rsa_full_path: "{{ easy_rsa_path}}{{easy_rsa_version}}/"

    - name: Create CA directory
      become: yes
      command: mkdir -p {{ item }}
      with_items:
      - "{{ openvpn_cert_dir }}"
      - "{{ easy_rsa_ca_dir }}"
  when: ansible_distribution == "CentOS"
  tags:
      - easy_rsa

- name: Create vars configuration file
  become: yes
  template:
    src: vars3.j2
    dest: "{{ easy_rsa_ca_dir }}/vars"
    owner: root
    group: root
    mode: 0644
  tags:
    - easy_rsa

- name: Prepare pki and CA
  become: yes
  shell: "{{ easy_rsa_full_path }}easyrsa --batch {{ item }}"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
  with_items:
  - "init-pki"
  - "build-ca nopass"
  tags:
    - easy_rsa

- name: Generate Diffie-Hellman parameters (this might take a while)
  become: yes
  shell: "{{ easy_rsa_full_path }}easyrsa gen-dh"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
  tags:
    - easy_rsa

- name: Generate server certificate and key
  become: yes
  shell: "{{ easy_rsa_full_path }}easyrsa --batch {{ item }} "
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
  with_items:
  - "gen-req {{ server_cn }} nopass"
  - "sign-req server {{ server_cn }}"
  tags:
    - easy_rsa

- name: Generate client certificate and key
  become: yes
  shell: "{{ easy_rsa_full_path }}easyrsa --req-cn={{ item }} --batch gen-req  {{ item }} nopass"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
  with_items: "{{ client_cn_list}}" 
  tags:
    - easy_rsa

- name: Generate client certificate and key
  become: yes
  shell: "{{ easy_rsa_full_path }}easyrsa --batch sign-req client {{ item }}"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
  with_items: "{{ client_cn_list}}"
  tags:
    - easy_rsa

- name: Generate revoked cert list
  become: yes
  shell: "{{ easy_rsa_full_path }}easyrsa gen-crl"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
  tags:
    - easy_rsa

- name: Generate revoked cert list
  become: yes
  shell: "{{ easy_rsa_full_path }}easyrsa gen-crl"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
  tags:
    - easy_rsa

### from this point we start configuring openvpn so we move to install step of other role